---
name: user-accounts-server
director_uuid: 3606f4d1-c2f8-48bc-913d-b5a4012e81ec
compilation:
  cloud_properties:
    ram: 2048
    disk: 4096
    cpu: 2
  network: default
  reuse_compilation_vms: true
  workers: 1
jobs:
- instances: 1
  name: useradd
  networks:
  - default:
    - dns
    - gateway
    name: default
    static_ips:
    - 10.244.0.66
  persistent_disk: 16
  resource_pool: user-accounts_pool
  templates:
  - { release: user-accounts, name: useradd }
  properties:
    users:
    - username: test
networks:
- name: default
  subnets:
  - range: 10.244.0.64/30
    dns:
      - 8.8.8.8
    gateway: 10.244.0.65
    static: [10.244.0.66]
    cloud_properties: {}
  - range: 10.244.0.68/30
    dns:
      - 8.8.8.8
    gateway: 10.244.0.69
    cloud_properties: {}
releases:
  - name: user-accounts
    version: latest
  - name: newrelic
    version: latest
resource_pools:
- cloud_properties:
    ram: 2048
    disk: 8192
    cpu: 1
  name: user-accounts_pool
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000 - 600000
  max_in_flight: 8
  serial: false
  update_watch_time: 30000 - 600000
